# Generated by Django 3.1.1 on 2020-10-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='time_for_ending',
            field=models.TimeField(auto_now=True, verbose_name='Время прохождения'),
        ),
    ]
