# Generated by Django 3.1.1 on 2020-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_testresult_time_for_ending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата прохождения теста'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='time_for_ending',
            field=models.TimeField(default='00:00', verbose_name='Время прохождения'),
        ),
    ]
