# Generated by Django 3.1.1 on 2020-10-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20201008_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата прохождения теста и время прохождения теста'),
        ),
    ]
