# Generated by Django 3.1.1 on 2020-10-08 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('topic', '0003_auto_20201006_1541'),
        ('account', '0004_auto_20201008_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='topic.topics',
                                    verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
