# Generated by Django 3.1.1 on 2020-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_testresult_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Занесенно в журнал'),
        ),
    ]
