# Generated by Django 3.1.1 on 2020-10-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_testresult_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='mark',
            field=models.IntegerField(default=0, max_length=3, verbose_name='Отметка'),
        ),
    ]
