# Generated by Django 3.1.1 on 2020-10-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_testresult_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='last_name',
            field=models.CharField(default='', max_length=128, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testresult',
            name='mark',
            field=models.IntegerField(default=0, verbose_name='Отметка'),
        ),
    ]
