# Generated by Django 3.1.1 on 2020-10-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20201008_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='first_name',
            field=models.CharField(default='', max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
