# Generated by Django 3.1.1 on 2020-09-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200925_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответ'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Вопрос'},
        ),
    ]
