# Generated by Django 3.1.1 on 2020-09-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200925_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='question',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='home.questions'),
        ),
    ]
