# Generated by Django 3.1.1 on 2020-09-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200926_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(auto_created=True, default=None, max_length=256, verbose_name='Сессия')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
            ],
        ),
        migrations.AlterField(
            model_name='types',
            name='type',
            field=models.CharField(max_length=256, verbose_name='Тип'),
        ),
    ]
