# Generated by Django 3.1.1 on 2020-09-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200926_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='session',
            field=models.CharField(auto_created=True, blank=True, default=None, max_length=256, null=True, verbose_name='Сессия'),
        ),
    ]
