# Generated by Django 3.1.1 on 2020-09-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200926_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='session',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Сессия'),
        ),
    ]
