# Generated by Django 3.1.1 on 2020-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200927_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='session',
            field=models.CharField(max_length=256, verbose_name='Сессия'),
        ),
    ]
