# Generated by Django 3.1.1 on 2020-09-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200927_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
