# Generated by Django 3.1.1 on 2020-09-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200927_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='type',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
