# Generated by Django 3.1.1 on 2020-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_answers_questions_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='hint',
            field=models.CharField(max_length=32, verbose_name='Подсказка'),
        ),
    ]
